import { Container } from "@/components/container";

export default function PrivacyPolicy() {
  return (
    <div className="min-h-screen bg-white dark:bg-black">
      <Container>
        <div className="py-20">
          <div className="mx-auto max-w-4xl">
            <div className="text-center mb-12">
              <h1 className="text-4xl font-bold text-neutral-900 dark:text-neutral-100 mb-4">
                Privacy Policy
              </h1>
              <p className="text-neutral-600 dark:text-neutral-400">
                Last updated: 06/16/2025 | Effective date: Aug 30, 2018
              </p>
            </div>

            <div className="space-y-8 text-neutral-700 dark:text-neutral-300">
              <div className="bg-neutral-50 dark:bg-neutral-900 rounded-lg p-6">
                <p className="mb-4">
                  <strong>AETHER METRICS LLC</strong> ("us", "we", or "our") operates the www.aethermetrics.com website and the AETHER METRICS product (the "Service").
                </p>
                <p className="mb-4">
                  This page informs you of our policies regarding the collection, use, and disclosure of personal data when you use our Service and the choices you have associated with that data.
                </p>
                <p>
                  We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy.
                </p>
              </div>

              <section>
                <h2 className="text-2xl font-bold text-neutral-900 dark:text-neutral-100 mb-4">Definitions</h2>
                
                <div className="space-y-4">
                  <div>
                    <h3 className="font-semibold mb-2">Personal Data</h3>
                    <p>Personal Data means data about a living individual who can be identified from those data.</p>
                  </div>
                  
                  <div>
                    <h3 className="font-semibold mb-2">Usage Data</h3>
                    <p>Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself.</p>
                  </div>
                  
                  <div>
                    <h3 className="font-semibold mb-2">Cookies</h3>
                    <p>Cookies are small pieces of data stored on your device (computer or mobile device).</p>
                  </div>
                </div>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-neutral-900 dark:text-neutral-100 mb-4">Information Collection and Use</h2>
                <p className="mb-4">We collect several different types of information for various purposes to provide and improve our Service to you.</p>
                
                <h3 className="text-xl font-semibold mb-3">Personal Data</h3>
                <p className="mb-4">While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you. This may include:</p>
                <ul className="list-disc list-inside mb-4 space-y-1">
                  <li>Email address</li>
                  <li>First name and last name</li>
                  <li>Cookies and Usage Data</li>
                </ul>
                
                <h3 className="text-xl font-semibold mb-3">Usage Data</h3>
                <p className="mb-4">We may also collect information about how the Service is accessed and used. This Usage Data may include information such as your computer&apos;s Internet Protocol address, browser type, browser version, the pages of our Service that you visit, the time and date of your visit, and other diagnostic data.</p>
                
                <h3 className="text-xl font-semibold mb-3">Tracking & Cookies Data</h3>
                <p className="mb-4">We use cookies and similar tracking technologies to track the activity on our Service and hold certain information. Examples of Cookies we use:</p>
                <ul className="list-disc list-inside space-y-1">
                  <li><strong>Session Cookies:</strong> We use Session Cookies to operate our Service</li>
                  <li><strong>Preference Cookies:</strong> We use Preference Cookies to remember your preferences and various settings</li>
                  <li><strong>Security Cookies:</strong> We use Security Cookies for security purposes</li>
                </ul>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-neutral-900 dark:text-neutral-100 mb-4">Use of Data</h2>
                <p className="mb-4">AETHER METRICS LLC uses the collected data for various purposes:</p>
                <ul className="list-disc list-inside space-y-1">
                  <li>To provide and maintain our Service</li>
                  <li>To notify you about changes to our Service</li>
                  <li>To allow you to participate in interactive features of our Service</li>
                  <li>To provide customer support</li>
                  <li>To gather analysis or valuable information so that we can improve our Service</li>
                  <li>To monitor the usage of our Service</li>
                  <li>To detect, prevent and address technical issues</li>
                </ul>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-neutral-900 dark:text-neutral-100 mb-4">Data Deletion Request</h2>
                <p className="mb-4">If you wish to delete your account or any data processed by AETHER METRICS, you can do so by following these steps:</p>
                <ul className="list-disc list-inside space-y-2">
                  <li><strong>Contact Us Directly:</strong> Send an email to support@aethermetrics.com with the subject line "Data Deletion Request."</li>
                  <li><strong>Account Deletion:</strong> Log in to your AETHER METRICS account, navigate to Account Settings, and follow the steps under the Delete Account section.</li>
                  <li><strong>Third-Party Data:</strong> Remove permissions and data shared with AETHER METRICS through third-party APIs.</li>
                </ul>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-neutral-900 dark:text-neutral-100 mb-4">GDPR Data Protection Rights</h2>
                <p className="mb-4">If you are a resident of the European Economic Area (EEA), you have certain data protection rights:</p>
                <ul className="list-disc list-inside space-y-2">
                  <li><strong>The right to access, update or delete</strong> the information we have on you</li>
                  <li><strong>The right of rectification</strong> - You have the right to have your information rectified if that information is inaccurate or incomplete</li>
                  <li><strong>The right to object</strong> - You have the right to object to our processing of your Personal Data</li>
                  <li><strong>The right of restriction</strong> - You have the right to request that we restrict the processing of your personal information</li>
                  <li><strong>The right to data portability</strong> - You have the right to be provided with a copy of the information we have on you</li>
                  <li><strong>The right to withdraw consent</strong> - You also have the right to withdraw your consent at any time</li>
                </ul>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-neutral-900 dark:text-neutral-100 mb-4">Security of Data</h2>
                <p>The security of your data is important to us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.</p>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-neutral-900 dark:text-neutral-100 mb-4">Children&apos;s Privacy</h2>
                <p className="mb-4">Our Service does not address anyone under the age of 18 ("Children").</p>
                <p>We do not knowingly collect personally identifiable information from anyone under the age of 18. If you are a parent or guardian and you are aware that your child has provided us with Personal Data, please contact us.</p>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-neutral-900 dark:text-neutral-100 mb-4">Changes to This Privacy Policy</h2>
                <p className="mb-4">We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.</p>
                <p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
              </section>

              <section>
                <h2 className="text-2xl font-bold text-neutral-900 dark:text-neutral-100 mb-4">Contact Us</h2>
                <p className="mb-4">
                  If you have any questions about this Privacy Policy, please contact us at{" "}
                  <a href="mailto:support@aethermetrics.com" className="text-blue-600 dark:text-blue-400 hover:underline">
                    support@aethermetrics.com
                  </a>
                </p>
                <p>
                  <strong>AETHER METRICS LLC</strong><br />
                  www.aethermetrics.com
                </p>
              </section>
            </div>
          </div>
        </div>
      </Container>
    </div>
  );
} 